"""The contribution corpus model and the GitHub mirror that fills it.

No network and no database. `submission_api/contributions.py` is pure, and the mirror is driven
through an injected `httpx` transport that serves a tarball built in memory — so the archive
walk, the conditional-request bookkeeping and the rate-limit backoff are all exercised against
the same code paths that talk to github.com, without talking to it.

The HTTP surface is `tests/test_api_contributions.py`.
"""

from __future__ import annotations

import asyncio
import io
import json
import tarfile
from datetime import UTC, datetime

import pytest

pytest.importorskip("httpx", reason="the contribution mirror needs the service extra")

import httpx

from submission_api.contributions import (
    ContributionSnapshot,
    ContributionsError,
    parse_empty_target,
    parse_target,
)
from submission_api.github import (
    GitHubContributionMirror,
    UnavailableContributionMirror,
)

REPOSITORY = "conjectures-io/conjectures-contribution"
AUTHOR = "7e" + "0" * 62
OTHER_AUTHOR = "d1" + "0" * 62
COLDKEY = "5G4LNpyehdqUU6CtP7SYSZLFK5mxzTCihXHiDxmbfHwAAW7L"
HOTKEY = "5FqLp5QmNRiHGyj3xbLVnDHfCx25qxJX5CUhpndF9GFfZZiK"
COMMIT = "4c1fddbbc167fcb8366101ff4d105410d3580853"
OTHER_COMMIT = "1c8978d174504235c16f0f6a87c56d4eb734baf0"


def run(coroutine):
    return asyncio.run(coroutine)


def entry(
    *,
    contribution_id: str = "a" * 64,
    author: str = AUTHOR,
    added: str = "2026-09-03",
    kind: str = "lemma",
    mode: str = "formalized",
    title: str = "Extremal witness and monotonicity API",
    declarations: tuple[str, ...] = ("Contribution.Erdos535BasicAPI.f_le",),
    coldkey: str | None = COLDKEY,
    hotkey: str | None = HOTKEY,
) -> dict:
    return {
        "added": added,
        "artifacts": ["script.lean", "sources.md"],
        "author": author,
        "coldkey": coldkey,
        "contribution_id": contribution_id,
        "declarations": list(declarations),
        "hotkey": hotkey,
        "kind": kind,
        "mode": mode,
        "parents": [],
        "path": f"{contribution_id}/",
        "tasks_commit": "379fc0298dc146df549e7061c3ede0353a5bb51f",
        "title": title,
    }


def index(
    *,
    target: str = "erdos-535",
    reward_target_id: str | None = "fc-target:Erdos535.erdos_535",
    contributions: tuple[dict, ...] | None = None,
    open_: bool = True,
) -> dict:
    return {
        "contribution_count": len(contributions or (entry(),)),
        "contributions": list(contributions if contributions is not None else (entry(),)),
        "open": open_,
        "problem_id": f"fc-379fc029-{target}-problem",
        "reward_target_id": reward_target_id,
        "schema_version": 2,
        "target": target,
    }


PAGE = (
    "# {target}\n\n"
    "<!-- Generated by `contrib-admin index`. Do not edit by hand. -->\n\n"
    "**Problem** `fc-379fc029-{target}-problem` · "
    "**Reward target** `fc-target:{theorem}`\n"
)


# --- Parsing -----------------------------------------------------------------------------------


def test_a_target_index_parses_into_rows_joined_to_this_apis_conjecture_slug():
    row = parse_target(index(), directory="erdos-535")

    assert row.target == "erdos-535"
    assert row.reward_target_id == "fc-target:Erdos535.erdos_535"
    # The corpus's target slug and this API's conjecture slug are different naming schemes over
    # the same theorem. The join is the reward target, never the slug string.
    assert row.conjecture_slug == "erdos535-erdos-535"
    assert row.conjecture_slug != row.target
    assert row.contribution_count == 1
    assert row.contributions[0].declarations == ("Contribution.Erdos535BasicAPI.f_le",)
    assert row.contributions[0].rewarded is True


def test_an_index_that_names_a_different_target_than_its_directory_is_refused():
    """A copied rather than generated index would put contributions on the wrong conjecture."""
    with pytest.raises(ContributionsError):
        parse_target(index(target="erdos-100"), directory="erdos-535")


@pytest.mark.parametrize(
    "mutate",
    [
        pytest.param({"schema_version": 3}, id="unknown schema"),
        pytest.param({"contributions": {}}, id="contributions not a list"),
        pytest.param({"target": "Erdos-535"}, id="target not a slug"),
    ],
)
def test_a_malformed_index_raises_rather_than_yielding_a_partial_row(mutate):
    payload = index() | mutate
    with pytest.raises(ContributionsError):
        parse_target(payload, directory=payload.get("target", "erdos-535"))


@pytest.mark.parametrize(
    "field, value",
    [
        ("contribution_id", "not-hex"),
        ("author", "z" * 64),
        ("added", "the third of September"),
        ("title", ""),
    ],
)
def test_a_malformed_contribution_raises(field, value):
    with pytest.raises(ContributionsError):
        parse_target(
            index(contributions=(entry() | {field: value},)), directory="erdos-535"
        )


def test_a_contribution_that_opted_out_of_a_reward_is_absent_not_zero():
    row = parse_target(
        index(contributions=(entry(coldkey=None, hotkey=None),)), directory="erdos-535"
    )
    item = row.contributions[0]

    assert item.coldkey is None
    assert item.hotkey is None
    assert item.rewarded is False


def test_an_unusable_wallet_is_dropped_rather_than_failing_the_whole_target():
    """One contributor's typo must not hide every correct row on the target."""
    row = parse_target(
        index(contributions=(entry(coldkey="not a wallet"), entry(contribution_id="b" * 64))),
        directory="erdos-535",
    )

    assert row.contribution_count == 2
    assert row.contributions[1].coldkey is None or row.contributions[0].coldkey is None


def test_an_index_naming_no_reward_target_has_no_conjecture_slug():
    row = parse_target(index(reward_target_id=None), directory="erdos-535")

    assert row.reward_target_id is None
    assert row.conjecture_slug is None


def test_a_target_with_only_a_generated_page_is_an_empty_target_with_a_full_identity():
    """152 of the corpus's 209 targets are in this state; dropping them loses the whole
    "which conjectures need work" question."""
    row = parse_empty_target(
        PAGE.format(target="erdos-1049", theorem="Erdos1049.erdos_1049"),
        directory="erdos-1049",
    )

    assert row.contribution_count == 0
    assert row.reward_target_id == "fc-target:Erdos1049.erdos_1049"
    assert row.conjecture_slug == "erdos1049-erdos-1049"


def test_a_page_without_the_generated_identity_line_still_yields_the_target():
    row = parse_empty_target("# erdos-9\n\nsome prose\n", directory="erdos-9")

    assert row.target == "erdos-9"
    assert row.reward_target_id is None
    assert row.conjecture_slug is None


# --- Snapshot ----------------------------------------------------------------------------------


def snapshot(*targets, pending=(), unreadable=()) -> ContributionSnapshot:
    return ContributionSnapshot.build(
        repository=REPOSITORY,
        branch="main",
        head_commit=COMMIT,
        fetched_at=datetime(2026, 9, 3, 12, 0, tzinfo=UTC),
        targets=targets,
        pending=pending,
        unreadable=unreadable,
    )


def test_a_target_resolves_by_all_four_of_its_names():
    row = parse_target(index(), directory="erdos-535")
    built = snapshot(row)

    for name in ("erdos-535", "erdos535-erdos-535", "fc-target:Erdos535.erdos_535"):
        assert built.target(name) is row
    assert built.target(row.problem_id) is row
    assert built.target("erdos-999") is None


def test_a_contribution_resolves_by_full_id_and_by_unambiguous_prefix():
    built = snapshot(parse_target(index(), directory="erdos-535"))

    assert built.contribution("a" * 64) is not None
    assert built.contribution("a" * 12) is not None
    # Too short to be an identifier rather than a scan.
    assert built.contribution("aaaa") is None


def test_an_ambiguous_prefix_resolves_to_nothing_rather_than_to_the_first_match():
    built = snapshot(
        parse_target(
            index(
                contributions=(
                    entry(contribution_id="ab" + "1" * 62),
                    entry(contribution_id="ab" + "2" * 62),
                )
            ),
            directory="erdos-535",
        )
    )

    assert built.contribution("ab" + "1" * 62) is not None
    assert built.contribution("ab123456") is None


def test_the_author_cross_cut_reports_a_coldkey_two_signing_keys_share():
    built = snapshot(
        parse_target(
            index(
                contributions=(
                    entry(contribution_id="a" * 64, author=AUTHOR),
                    entry(contribution_id="b" * 64, author=OTHER_AUTHOR),
                )
            ),
            directory="erdos-535",
        )
    )

    assert {row.author for row in built.authors} == {AUTHOR, OTHER_AUTHOR}
    assert all(row.shared_coldkey for row in built.authors)


def test_an_unfetched_snapshot_is_not_an_empty_one():
    """The distinction the endpoints spend a 503 on."""
    assert ContributionSnapshot.empty(repository=REPOSITORY).available is False
    assert snapshot().available is True


def test_the_snapshot_orders_contributions_newest_first_with_a_stable_tiebreak():
    built = snapshot(
        parse_target(
            index(
                contributions=(
                    entry(contribution_id="a" * 64, added="2026-08-01"),
                    entry(contribution_id="c" * 64, added="2026-09-01"),
                    entry(contribution_id="b" * 64, added="2026-09-01"),
                )
            ),
            directory="erdos-535",
        )
    )

    assert [item.contribution_id[0] for item in built.contributions] == ["c", "b", "a"]


# --- The GitHub mirror -------------------------------------------------------------------------


def tarball(indexes: dict[str, dict], pages: dict[str, str] | None = None) -> bytes:
    """An archive shaped exactly like GitHub's: one wrapper directory over the repository."""
    buffer = io.BytesIO()
    with tarfile.open(fileobj=buffer, mode="w:gz") as bundle:
        for target, payload in indexes.items():
            _add(bundle, f"repo-sha/contributions/{target}/index.json", json.dumps(payload))
        for target, page in (pages or {}).items():
            _add(bundle, f"repo-sha/contributions/{target}/index.md", page)
    return buffer.getvalue()


def _add(bundle: tarfile.TarFile, name: str, text: str) -> None:
    raw = text.encode("utf-8")
    info = tarfile.TarInfo(name)
    info.size = len(raw)
    bundle.addfile(info, io.BytesIO(raw))


class FakeGitHub:
    """A transport standing in for the REST API, counting what it was actually asked for."""

    def __init__(
        self,
        *,
        commit: str = COMMIT,
        archive: bytes | None = None,
        pulls: list | None = None,
    ) -> None:
        self.commit = commit
        self.archive = archive if archive is not None else tarball({"erdos-535": index()})
        self.pulls = pulls if pulls is not None else []
        self.requests: list[str] = []
        self.commit_etag = "W/\"commit-1\""
        self.pulls_etag = "W/\"pulls-1\""

    def handler(self, request: httpx.Request) -> httpx.Response:
        path = request.url.path
        self.requests.append(path)
        conditional = request.headers.get("if-none-match")
        if path.endswith("/commits/main"):
            if conditional == self.commit_etag:
                return httpx.Response(304, headers={"ETag": self.commit_etag})
            return httpx.Response(
                200, json={"sha": self.commit}, headers={"ETag": self.commit_etag}
            )
        if path.endswith("/pulls"):
            if conditional == self.pulls_etag:
                return httpx.Response(304, headers={"ETag": self.pulls_etag})
            return httpx.Response(
                200, json=self.pulls, headers={"ETag": self.pulls_etag}
            )
        if "/tarball/" in path:
            return httpx.Response(200, content=self.archive)
        return httpx.Response(404, json={"message": "Not Found"})


def mirror(github: FakeGitHub, **kwargs) -> GitHubContributionMirror:
    return GitHubContributionMirror(
        repository=REPOSITORY,
        api_base_url="https://api.github.test",
        client=httpx.AsyncClient(
            transport=httpx.MockTransport(github.handler),
            base_url="https://api.github.test",
        ),
        **kwargs,
    )


def test_a_first_poll_reads_the_whole_corpus_from_one_archive():
    github = FakeGitHub(
        archive=tarball(
            {"erdos-535": index()},
            pages={
                "erdos-1049": PAGE.format(
                    target="erdos-1049", theorem="Erdos1049.erdos_1049"
                )
            },
        )
    )
    subject = mirror(github)

    assert run(subject.refresh()) is True
    built = subject.snapshot()

    assert built.head_commit == COMMIT
    assert len(built.targets) == 2
    assert len(built.contributions) == 1
    assert built.target("erdos-1049").contribution_count == 0
    assert sum(1 for path in github.requests if "tarball" in path) == 1
    run(subject.aclose())


def test_a_poll_where_nothing_moved_costs_two_conditional_requests_and_no_archive():
    """The steady state. A 304 does not count against GitHub's hourly budget."""
    github = FakeGitHub()
    subject = mirror(github)
    run(subject.refresh())
    github.requests.clear()

    assert run(subject.refresh()) is False
    assert [path.rsplit("/", 1)[-1] for path in github.requests] == ["main", "pulls"]
    run(subject.aclose())


def test_a_moved_head_rebuilds_the_snapshot():
    github = FakeGitHub()
    subject = mirror(github)
    run(subject.refresh())

    github.commit = OTHER_COMMIT
    github.commit_etag = 'W/"commit-2"'
    github.archive = tarball({"erdos-535": index(), "erdos-100": index(target="erdos-100")})

    assert run(subject.refresh()) is True
    assert subject.snapshot().head_commit == OTHER_COMMIT
    assert len(subject.snapshot().targets) == 2
    run(subject.aclose())


def test_a_failed_poll_leaves_the_previous_snapshot_serving():
    """A stale corpus is a far better answer than an empty one."""
    github = FakeGitHub()
    subject = mirror(github)
    run(subject.refresh())
    good = subject.snapshot()

    github.commit_etag = 'W/"commit-2"'
    github.archive = b"not a tarball"

    assert run(subject.refresh()) is False
    assert subject.snapshot() is good
    assert subject.snapshot().available is True
    run(subject.aclose())


def test_a_failed_first_load_is_retried_rather_than_answered_304_forever():
    """The bug conditional requests invite: caching a validator for a commit that never loaded.

    The head fetch succeeds, the archive read fails. If the head `ETag` were stored anyway, every
    later poll would be told `304`, the mirror would never attempt that commit again, and it would
    sit unavailable indefinitely while looking like a healthy quiet loop.
    """
    github = FakeGitHub(archive=b"not a tarball")
    subject = mirror(github)

    assert run(subject.refresh()) is False
    assert subject.snapshot().available is False

    github.archive = tarball({"erdos-535": index()})
    assert run(subject.refresh()) is True
    assert subject.snapshot().available is True
    run(subject.aclose())


def test_a_commit_whose_archive_failed_is_retried_without_waiting_for_a_new_commit():
    """The same trap one state later: a good snapshot serving, and a new commit that would not load."""
    github = FakeGitHub()
    subject = mirror(github)
    run(subject.refresh())

    github.commit = OTHER_COMMIT
    github.commit_etag = 'W/"commit-2"'
    github.archive = b"not a tarball"
    assert run(subject.refresh()) is False
    assert subject.snapshot().head_commit == COMMIT

    github.archive = tarball({"erdos-535": index(), "erdos-100": index(target="erdos-100")})
    assert run(subject.refresh()) is True
    assert subject.snapshot().head_commit == OTHER_COMMIT
    run(subject.aclose())


def test_an_archive_with_no_target_directories_is_refused_as_a_wrong_archive():
    github = FakeGitHub(archive=tarball({}))
    subject = mirror(github)

    assert run(subject.refresh()) is False
    assert subject.snapshot().available is False
    run(subject.aclose())


def test_one_unparseable_index_is_reported_rather_than_silently_dropped():
    archive = tarball({"erdos-535": index(), "erdos-100": {"schema_version": 99}})
    subject = mirror(FakeGitHub(archive=archive))

    assert run(subject.refresh()) is True
    built = subject.snapshot()

    assert len(built.targets) == 1
    assert [name for name, _ in built.unreadable] == ["erdos-100"]
    run(subject.aclose())


def test_an_oversized_archive_is_abandoned_rather_than_buffered_whole():
    github = FakeGitHub(archive=b"\x00" * 4096)
    subject = mirror(github, max_archive_bytes=1024)

    assert run(subject.refresh()) is False
    assert subject.snapshot().available is False
    run(subject.aclose())


def test_open_pull_requests_are_reported_apart_from_accepted_contributions():
    github = FakeGitHub(
        pulls=[
            {
                "number": 93,
                "title": "contribution: erdos-535",
                "draft": False,
                "created_at": "2026-09-03T07:19:54Z",
                "updated_at": "2026-09-03T07:21:48Z",
                "html_url": "https://github.com/x/y/pull/93",
                "user": {"login": "someone"},
                "head": {"ref": "contribution/62b7cf3d72d6"},
                "labels": [
                    {"name": "hotkey:5FqLp5QmNR"},
                    {"name": "target:erdos-535"},
                ],
            }
        ]
    )
    subject = mirror(github)
    run(subject.refresh())
    built = subject.snapshot()

    assert len(built.pending) == 1
    pending = built.pending[0]
    assert pending.target == "erdos-535"
    # Resolved against the merged corpus, because an open pull request names no reward target.
    assert pending.conjecture_slug == "erdos535-erdos-535"
    assert pending.hotkey == "5FqLp5QmNR"
    # Still one contribution: intent is not achievement.
    assert len(built.contributions) == 1
    run(subject.aclose())


def test_a_malformed_pull_request_is_skipped_without_losing_the_listing():
    github = FakeGitHub(pulls=[{"number": "not an int"}, {"nothing": True}])
    subject = mirror(github)

    assert run(subject.refresh()) is True
    assert subject.snapshot().pending == ()
    run(subject.aclose())


def test_a_rate_limit_refusal_backs_off_instead_of_retrying_into_the_penalty_box():
    clock = [0.0]

    class Throttled(FakeGitHub):
        def handler(self, request):
            self.requests.append(request.url.path)
            return httpx.Response(
                403,
                headers={"x-ratelimit-remaining": "0", "retry-after": "120"},
                json={"message": "rate limit exceeded"},
            )

    github = Throttled()
    subject = mirror(github, monotonic=lambda: clock[0])

    assert run(subject.refresh()) is False
    assert len(github.requests) == 1

    # Still inside the backoff: no request is made at all.
    clock[0] = 60.0
    assert run(subject.refresh()) is False
    assert len(github.requests) == 1

    clock[0] = 200.0
    assert run(subject.refresh()) is False
    assert len(github.requests) == 2
    run(subject.aclose())


def test_the_unavailable_mirror_reports_an_unread_corpus_rather_than_an_empty_one():
    built = UnavailableContributionMirror().snapshot()

    assert built.available is False
    assert built.contributions == ()


@pytest.mark.parametrize(
    "kwargs",
    [
        pytest.param({"repository": "not-a-repository"}, id="repository"),
        pytest.param({"branch": "../../etc"}, id="branch"),
        pytest.param({"timeout_seconds": 0}, id="timeout"),
    ],
)
def test_the_mirror_refuses_a_configuration_it_cannot_safely_interpolate(kwargs):
    with pytest.raises(ValueError):
        GitHubContributionMirror(**kwargs)
