"""Per-request Axiom events, attributed to the endpoint that answered.

One event per answered request, `request_completed`, carrying the two labels the vocabulary is
built on plus the request's own facts:

* **source** — the area of the API, resolved from the path by `source_for_path`. `/v1/me/credits`
  is `api-me`, `/v1/submissions/intents/{id}/confirm` is `api-intents`. A single `api` label would
  make every dashboard start by re-deriving this from a path string.
* **severity** — from the status: `2xx`/`3xx` are `info`, `4xx` is `warning`, `5xx` is `error`. So
  "is the API healthy" is a severity filter rather than a status-code range someone has to
  remember.
* **endpoint** — the *route template*, `/v1/submissions/{submission_id}`, not the path that was
  requested. That is what makes the events groupable: a per-path breakdown of a UUID-keyed route
  has one row per request. It is also the safer of the two — see `_endpoint`.

Placed outermost in the middleware stack (added last in `app.py`), so it observes every response
the process emits, including the rate limiter's `429` and the write guard's `403`, which are
generated by middleware and never reach a route.

Raw ASGI, like every other layer here, and for the same reason `middleware.py` gives:
`BaseHTTPMiddleware` buffers the response body through a task group, which would undo the streaming
byte cap that `POST /v1/submissions` relies on to kill a hostile body mid-flight. This middleware
reads `http.response.start` and passes every message through untouched.
"""

from __future__ import annotations

import logging
import time
from collections.abc import Iterable, Mapping
from typing import Final

from starlette.types import ASGIApp, Message, Receive, Scope, Send

from conjectures_subnet.axiom import Severity, Source, get_axiom, request_id
from conjectures_subnet.axiom.context import new_correlation_id
from submission_api.errors import SCOPE_REASON_CODE, SCOPE_REQUEST_ID
from submission_api.middleware import client_address

logger = logging.getLogger("submission_api.observability")

# The header the correlation id is echoed in, so an operator holding a failed response can find
# the request in Axiom. Read-only for the client: an id it supplies is ignored, because a
# client-chosen key would let one caller collide its requests with another's.
REQUEST_ID_HEADER: Final = "X-Request-Id"

# Never reported. The orchestrator polls liveness and readiness on a fixed interval and the docs
# are a developer's browser; both would drown the dataset in events that say nothing about the
# subnet.
EXEMPT_PREFIXES: Final = ("/healthz", "/readyz", "/docs", "/redoc", "/openapi.json")

# How much of the HTTP surface to report, from `AXIOM_REQUEST_EVENTS`.
REQUEST_EVENTS_ALL: Final = "all"
REQUEST_EVENTS_FAILURES: Final = "failures"
REQUEST_EVENTS_OFF: Final = "off"
REQUEST_EVENT_MODES: Final = (
    REQUEST_EVENTS_ALL,
    REQUEST_EVENTS_FAILURES,
    REQUEST_EVENTS_OFF,
)

# Longest prefix first. `/v1/submissions/intents` has to be tested before `/v1/submissions`, or
# every intent call would be attributed to the extrinsic submission path they share a prefix with.
_AREAS: Final[tuple[tuple[str, Source], ...]] = (
    ("/v1/submissions/intents", "api-intents"),
    ("/v1/submissions/preflight", "api-intents"),
    # The one-call website path is the credit surface too — same audience, same money, same
    # `intent_*` events underneath — so it reports as one area with the three-call flow rather
    # than as part of the hotkey-signed extrinsic path it shares a prefix with.
    ("/v1/submissions/web", "api-intents"),
    ("/v1/submissions", "api-submissions"),
    ("/v1/auth", "api-auth"),
    ("/v1/me", "api-me"),
    ("/v1/catalog", "api-catalog"),
    ("/v1/contributions", "api-contributions"),
    ("/v1/results", "api-results"),
    ("/v1/tasks", "api-tasks"),
    ("/v1/system", "api-system"),
    ("/healthz", "api-health"),
    ("/readyz", "api-health"),
)

# A user agent is client-supplied and unbounded; truncated so one caller cannot inflate every
# event it produces.
_MAX_USER_AGENT: Final = 200
# An unmatched path is also client-supplied. Same reasoning.
_MAX_PATH: Final = 200


def source_for_path(path: str, *, default: Source = "api") -> Source:
    """Which area of the API owns a path. The `source` label on every request event."""
    for prefix, area in _AREAS:
        if path == prefix or path.startswith(f"{prefix}/"):
            return area
    return default


def severity_for_status(status: int) -> Severity:
    """A response status as a severity.

    `4xx` is a warning rather than an error because most of them are correct behaviour — a miner
    submitting a malformed bundle gets a `422` and the API did its job. What makes them worth a
    non-info severity is that a *rate* of them is a signal: a spike in `401`s is either an attack
    or a client that broke.
    """
    if status >= 500:
        return Severity.ERROR
    if status >= 400:
        return Severity.WARNING
    return Severity.INFO


def request_event_mode(environ: Mapping[str, str]) -> str:
    """`AXIOM_REQUEST_EVENTS`, defaulting to `all`. An unrecognised value falls back loudly.

    `failures` is there for a deployment whose public catalog traffic would dominate the dataset:
    it keeps every `4xx` and `5xx` and drops the successes, so the alerting still works and the
    volume does not. `off` leaves the explicit domain events and the logging bridge in place.
    """
    raw = environ.get("AXIOM_REQUEST_EVENTS", "").strip().lower()
    if not raw:
        return REQUEST_EVENTS_ALL
    if raw not in REQUEST_EVENT_MODES:
        logger.warning(
            "AXIOM_REQUEST_EVENTS=%r is not one of %s; reporting all requests",
            raw,
            ", ".join(REQUEST_EVENT_MODES),
        )
        return REQUEST_EVENTS_ALL
    return raw


class AxiomRequestMiddleware:
    """Emits one `request_completed` event per request and tags the request with a correlation id.

    The correlation id is set on a `ContextVar` before the request runs, so every log record the
    handlers and the database layer produce underneath carries the same `request_id` as this
    event — see `conjectures_subnet.axiom.context`. That is the difference between a dataset you
    can reconstruct one call from and a pile of rows with adjacent timestamps.
    """

    def __init__(
        self,
        app: ASGIApp,
        *,
        trusted_proxy_hops: int = 0,
        mode: str = REQUEST_EVENTS_ALL,
        exempt: Iterable[str] = EXEMPT_PREFIXES,
    ) -> None:
        self._app = app
        self._trusted_proxy_hops = trusted_proxy_hops
        self._mode = mode
        self._exempt = tuple(exempt)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        path = scope.get("path", "")
        if (
            scope["type"] != "http"
            or self._mode == REQUEST_EVENTS_OFF
            or path.startswith(self._exempt)
        ):
            await self._app(scope, receive, send)
            return

        correlation = new_correlation_id()
        token = request_id.set(correlation)
        # Also on the scope, because Starlette's `Exception` handler runs outside every layer added
        # with `add_middleware` and so cannot see the ContextVar. See `errors.SCOPE_REQUEST_ID`.
        scope[SCOPE_REQUEST_ID] = correlation
        started = time.perf_counter()
        status: int | None = None

        async def send_with_id(message: Message) -> None:
            nonlocal status
            if message["type"] == "http.response.start":
                status = message.get("status", 500)
                headers = list(message.get("headers", []))
                headers.append(
                    (
                        REQUEST_ID_HEADER.lower().encode("latin-1"),
                        correlation.encode("latin-1"),
                    )
                )
                message = {**message, "headers": headers}
            await send(message)

        try:
            await self._app(scope, receive, send_with_id)
        except Exception:
            # Starlette's `ServerErrorMiddleware` wraps the whole stack, so it is *outside* this
            # layer: an unhandled exception propagates through here first, and the `500` it then
            # sends goes out through its own `send` rather than the wrapper above. So `status` is
            # still None, and nothing would report the request at all.
            #
            # It answers `500` unconditionally — with `unhandled_error_handler`'s problem document
            # when one is registered, which `app.py` always does, and a bare `Internal Server
            # Error` otherwise. Recording that status here is what keeps 5xx on the request stream.
            #
            # No `unexpected_error` from this layer: `unhandled_error_handler` emits one, with the
            # traceback and against this same request id, and two rows per failure is worse than
            # one. An exception that escapes *after* a response started leaves `status` set, and
            # falls through to the reporting below with whatever the route managed to send.
            if status is None:
                status = 500
            raise
        finally:
            # In `finally` rather than `else`, so a request answered with a `500` still reports its
            # status and duration on the request stream instead of vanishing from it.
            self._report(scope, path, status=status, started=started)
            request_id.reset(token)

    def _report(
        self, scope: Scope, path: str, *, status: int | None, started: float
    ) -> None:
        # No `http.response.start` means the connection went away before the app answered — a
        # disconnect, not an outcome, and there is no status to report on it.
        if status is None:
            return
        if self._mode == REQUEST_EVENTS_FAILURES and status < 400:
            return
        fields: dict[str, object] = {
            "endpoint": _endpoint(scope, path),
            "method": scope.get("method", ""),
            "status": status,
            "duration_ms": _elapsed_ms(started),
            "client": client_address(scope, self._trusted_proxy_hops),
            "user_agent": _header(scope, b"user-agent")[:_MAX_USER_AGENT],
        }
        # Left on the scope by the exception handlers in `errors.py`, so a refusal reports *why*
        # on the same event as the endpoint and the status rather than on a second row.
        reason_code = scope.get(SCOPE_REASON_CODE)
        if reason_code is not None:
            fields["reason_code"] = reason_code
        get_axiom().emit(
            severity=severity_for_status(status),
            source=source_for_path(path),
            event_type="request_completed",
            **fields,
        )


def _endpoint(scope: Scope, path: str) -> str:
    """The route template when one matched, else the requested path.

    The template and not the path, for two reasons. It groups: `/v1/results/{slug}` is one row in
    a latency breakdown rather than one per conjecture. And it cannot carry a secret — Starlette
    sets `scope["route"]` during routing, so by the time the response starts this is the shape of
    the endpoint with every path parameter's *value* left out.

    A request that matched no route has no template, so the raw path is reported instead — bounded,
    because at that point it is an arbitrary string somebody sent us. Query strings are never
    included: `?token=` on a sign-in callback is a credential, and telemetry is not where it goes.
    """
    route = scope.get("route")
    template = getattr(route, "path", None)
    if isinstance(template, str) and template:
        return template
    return path[:_MAX_PATH]


def _elapsed_ms(started: float) -> float:
    return round((time.perf_counter() - started) * 1000, 3)


def _header(scope: Scope, name: bytes) -> str:
    for key, value in scope.get("headers", ()):
        if key == name:
            return value.decode("latin-1", errors="replace")
    return ""


__all__ = [
    "EXEMPT_PREFIXES",
    "REQUEST_EVENTS_ALL",
    "REQUEST_EVENTS_FAILURES",
    "REQUEST_EVENTS_OFF",
    "REQUEST_EVENT_MODES",
    "REQUEST_ID_HEADER",
    "AxiomRequestMiddleware",
    "request_event_mode",
    "severity_for_status",
    "source_for_path",
]
