from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class ReasonCode(StrEnum):
    VERIFIED = "VERIFIED"
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    REPOSITORY_NOT_FOUND = "REPOSITORY_NOT_FOUND"
    REPOSITORY_COMMIT_MISMATCH = "REPOSITORY_COMMIT_MISMATCH"
    CATALOG_NOT_FOUND = "CATALOG_NOT_FOUND"
    THEOREM_NOT_FOUND = "THEOREM_NOT_FOUND"
    UNSUPPORTED_DECLARATION = "UNSUPPORTED_DECLARATION"
    ADAPTER_REQUIRED = "ADAPTER_REQUIRED"
    INVALID_TASK_MODE = "INVALID_TASK_MODE"
    INVALID_MANIFEST = "INVALID_MANIFEST"
    SOURCE_TYPE_CHANGED = "SOURCE_TYPE_CHANGED"
    TRUSTED_FILE_MODIFIED = "TRUSTED_FILE_MODIFIED"
    SUBMISSION_NOT_FOUND = "SUBMISSION_NOT_FOUND"
    SUBMISSION_TOO_LARGE = "SUBMISSION_TOO_LARGE"
    SUBMISSION_NOT_UTF8 = "SUBMISSION_NOT_UTF8"
    SUBMISSION_POLICY_VIOLATION = "SUBMISSION_POLICY_VIOLATION"
    WORKSPACE_ERROR = "WORKSPACE_ERROR"
    CHALLENGE_BUILD_FAILED = "CHALLENGE_BUILD_FAILED"
    SOLUTION_BUILD_FAILED = "SOLUTION_BUILD_FAILED"
    STATEMENT_MISMATCH = "STATEMENT_MISMATCH"
    UNPERMITTED_AXIOM = "UNPERMITTED_AXIOM"
    LEAN_KERNEL_REJECTED = "LEAN_KERNEL_REJECTED"
    NANODA_REJECTED = "NANODA_REJECTED"
    COMPARATOR_REJECTED = "COMPARATOR_REJECTED"
    TIMEOUT = "TIMEOUT"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    INTERNAL_ERROR = "INTERNAL_ERROR"


CONFIGURATION_REASONS = frozenset(
    {
        ReasonCode.INVALID_ARGUMENT,
        ReasonCode.REPOSITORY_NOT_FOUND,
        ReasonCode.REPOSITORY_COMMIT_MISMATCH,
        ReasonCode.CATALOG_NOT_FOUND,
        ReasonCode.THEOREM_NOT_FOUND,
        ReasonCode.UNSUPPORTED_DECLARATION,
        ReasonCode.ADAPTER_REQUIRED,
        ReasonCode.INVALID_TASK_MODE,
        ReasonCode.INVALID_MANIFEST,
        ReasonCode.SOURCE_TYPE_CHANGED,
        ReasonCode.TRUSTED_FILE_MODIFIED,
        ReasonCode.WORKSPACE_ERROR,
        ReasonCode.CHALLENGE_BUILD_FAILED,
        ReasonCode.INTERNAL_ERROR,
    }
)


@dataclass(frozen=True)
class VerifierError(Exception):
    reason: ReasonCode
    message: str

    def __str__(self) -> str:
        return self.message


def exit_code_for(reason: ReasonCode, accepted: bool = False) -> int:
    if accepted:
        return 0
    return 2 if reason in CONFIGURATION_REASONS else 1
